import { createAvatar } from "@dicebear/core";
import * as adventurer from "@dicebear/adventurer";
import * as adventurerNeutral from "@dicebear/adventurer-neutral";

const portraitMap = {
  "李昕纾": "/portraits/custom/lixinshu-web.webp",
  "韩立": "/portraits/generated/han-li.png",
  "陈巧倩": "/portraits/generated-ai/npc-002.svg",
  "钟卫娘": "/portraits/generated-ai/npc-003.svg",
  "刘靖": "/portraits/generated-ai/npc-004.svg",
  "吴风": "/portraits/generated-ai/npc-005.svg",
  "李化元": "/portraits/generated-ai/npc-006.svg",
  "雷万鹤": "/portraits/generated-ai/npc-007.svg",
  "红拂": "/portraits/generated-ai/npc-008.svg",
  "令狐老祖": "/portraits/generated-ai/npc-009.svg",
  "马师伯": "/portraits/generated-ai/npc-010.svg",
  "南宫婉": "/portraits/verified/%E5%8D%97%E5%AE%AB%E5%A9%89.jpg",
  "霓裳仙子": "/portraits/generated-ai/npc-012.svg",
  "穹老怪": "/portraits/generated-ai/npc-013.svg",
  "燕如嫣": "/portraits/generated-ai/npc-014.svg",
  "燕家老祖": "/portraits/generated-ai/npc-015.svg",
  "宣乐": "/portraits/generated-ai/npc-016.svg",
  "掩月长老": "/portraits/generated-ai/npc-017.svg",
  "霜华仙子": "/portraits/generated-ai/npc-018.svg",
  "月华真人": "/portraits/generated-ai/npc-019.svg",
  "素心师太": "/portraits/generated-ai/npc-020.svg",
  "涵云芝": "/portraits/generated-ai/npc-021.svg",
  "御灵子": "/portraits/generated-ai/npc-022.svg",
  "秦叶岭": "/portraits/generated-ai/npc-023.svg",
  "灵兽山主": "/portraits/generated-ai/npc-024.svg",
  "驭兽真人": "/portraits/generated-ai/npc-025.svg",
  "白鹤道人": "/portraits/generated-ai/npc-026.svg",
  "青鳞使": "/portraits/generated-ai/npc-027.svg",
  "黑虎上人": "/portraits/generated-ai/npc-028.svg",
  "百兽童子": "/portraits/generated-ai/npc-029.svg",
  "灵禽散人": "/portraits/generated-ai/npc-030.svg",
  "浮云子": "/portraits/generated-ai/npc-031.svg",
  "清虚散人": "/portraits/generated-ai/npc-032.svg",
  "明阳道人": "/portraits/generated-ai/npc-033.svg",
  "清虚门主": "/portraits/generated-ai/npc-034.svg",
  "青阳子": "/portraits/generated-ai/npc-035.svg",
  "玄清道人": "/portraits/generated-ai/npc-036.svg",
  "松纹真人": "/portraits/generated-ai/npc-037.svg",
  "白石散人": "/portraits/generated-ai/npc-038.svg",
  "观云师叔": "/portraits/generated-ai/npc-039.svg",
  "静虚道姑": "/portraits/generated-ai/npc-040.svg",
  "封岳": "/portraits/generated-ai/npc-041.svg",
  "刀坞老祖": "/portraits/generated-ai/npc-042.svg",
  "化刀坞主": "/portraits/generated-ai/npc-043.svg",
  "铁刀上人": "/portraits/generated-ai/npc-044.svg",
  "赤刃真人": "/portraits/generated-ai/npc-045.svg",
  "断水刀客": "/portraits/generated-ai/npc-046.svg",
  "冷锋子": "/portraits/generated-ai/npc-047.svg",
  "银刀客": "/portraits/generated-ai/npc-048.svg",
  "血刃散人": "/portraits/generated-ai/npc-049.svg",
  "鸣刀童子": "/portraits/generated-ai/npc-050.svg",
  "巨剑老祖": "/portraits/generated-ai/npc-051.svg",
  "铁罗": "/portraits/generated-ai/npc-052.svg",
  "剑眉修士": "/portraits/generated-ai/npc-053.svg",
  "巨剑门主": "/portraits/generated-ai/npc-054.svg",
  "玄剑真人": "/portraits/generated-ai/npc-055.svg",
  "重锋子": "/portraits/generated-ai/npc-056.svg",
  "裂岳剑修": "/portraits/generated-ai/npc-057.svg",
  "青虹剑客": "/portraits/generated-ai/npc-058.svg",
  "藏剑老人": "/portraits/generated-ai/npc-059.svg",
  "石剑道人": "/portraits/generated-ai/npc-060.svg",
  "天阙堡主": "/portraits/generated-ai/npc-061.svg",
  "辛如音": "/portraits/generated-ai/npc-062.svg",
  "齐云霄": "/portraits/generated-ai/npc-063.svg",
  "云露侍者": "/portraits/generated-ai/npc-064.svg",
  "天阙长老": "/portraits/generated-ai/npc-065.svg",
  "阵符先生": "/portraits/generated-ai/npc-066.svg",
  "玉阙真人": "/portraits/generated-ai/npc-067.svg",
  "司阵童子": "/portraits/generated-ai/npc-068.svg",
  "白阙散人": "/portraits/generated-ai/npc-069.svg",
  "灵阙居士": "/portraits/generated-ai/npc-070.svg",
  "王蝉": "/portraits/generated-ai/npc-071.svg",
  "王天胜": "/portraits/generated-ai/npc-072.svg",
  "鬼灵老祖": "/portraits/generated-ai/npc-073.svg",
  "碎魂真人": "/portraits/generated-ai/npc-074.svg",
  "董萱儿": "/portraits/generated-ai/npc-075.svg",
  "鬼灵门主": "/portraits/generated-ai/npc-076.svg",
  "血侍": "/portraits/generated-ai/npc-077.svg",
  "阴罗使": "/portraits/generated-ai/npc-078.svg",
  "黑煞教主": "/portraits/generated-ai/npc-079.svg",
  "炼魂童子": "/portraits/generated-ai/npc-080.svg",
  "合欢老魔": "/portraits/generated-ai/npc-081.svg",
  "田不缺": "/portraits/generated-ai/npc-082.svg",
  "云露老魔": "/portraits/generated-ai/npc-083.svg",
  "合欢宗主": "/portraits/generated-ai/npc-084.svg",
  "媚凝": "/portraits/generated-ai/npc-085.svg",
  "温夫人": "/portraits/generated-ai/npc-086.svg",
  "妙鹤仙子": "/portraits/generated-ai/npc-087.svg",
  "赤霞姬": "/portraits/generated-ai/npc-088.svg",
  "花影真人": "/portraits/generated-ai/npc-089.svg",
  "双修童子": "/portraits/generated-ai/npc-090.svg",
  "程天坤": "/portraits/generated-ai/npc-091.svg",
  "吕洛": "/portraits/generated-ai/npc-092.svg",
  "慕沛灵": "/portraits/generated-ai/npc-093.svg",
  "银月": "/portraits/verified/%E9%93%B6%E6%9C%88.jpg",
  "白凤峰主": "/portraits/generated-ai/npc-096.svg",
  "青竹真人": "/portraits/generated-ai/npc-097.svg",
  "落霞道人": "/portraits/generated-ai/npc-098.svg",
  "云梦仙子": "/portraits/generated-ai/npc-099.svg",
  "听松居士": "/portraits/generated-ai/npc-100.svg",
  "凌玉灵": "/portraits/generated-ai/npc-101.svg",
  "天星双圣": "/portraits/generated-ai/npc-102.svg",
  "温青": "/portraits/generated-ai/npc-103.svg",
  "凌啸风": "/portraits/generated-ai/npc-104.svg",
  "星宫长老": "/portraits/generated-ai/npc-105.svg",
  "白璧真人": "/portraits/generated-ai/npc-106.svg",
  "星璇使": "/portraits/generated-ai/npc-107.svg",
  "观星道人": "/portraits/generated-ai/npc-108.svg",
  "银辉仙子": "/portraits/generated-ai/npc-109.svg",
  "镇海法王": "/portraits/generated-ai/npc-110.svg",
  "紫灵": "/portraits/verified/%E7%B4%AB%E7%81%B5.jpg",
  "汪凝": "/portraits/generated-ai/npc-112.svg",
  "范静梅": "/portraits/generated-ai/npc-113.svg",
  "卓如婷": "/portraits/generated-ai/npc-114.svg",
  "妙音门主": "/portraits/generated-ai/npc-115.svg",
  "曲魂": "/portraits/generated-ai/npc-116.svg",
  "碧音仙子": "/portraits/generated-ai/npc-117.svg",
  "听潮女修": "/portraits/generated-ai/npc-118.svg",
  "玉箫道人": "/portraits/generated-ai/npc-119.svg",
  "海棠夫人": "/portraits/generated-ai/npc-120.svg",
  "六连殿主": "/portraits/generated-ai/npc-121.svg",
  "苗长老": "/portraits/generated-ai/npc-122.svg",
  "古长老": "/portraits/generated-ai/npc-123.svg",
  "许云": "/portraits/generated-ai/npc-124.svg",
  "六连执事": "/portraits/generated-ai/npc-125.svg",
  "海灯道人": "/portraits/generated-ai/npc-126.svg",
  "碧波客": "/portraits/generated-ai/npc-127.svg",
  "青蛟使": "/portraits/generated-ai/npc-128.svg",
  "离岛散人": "/portraits/generated-ai/npc-129.svg",
  "金霞掌柜": "/portraits/generated-ai/npc-130.svg",
  "六道极圣": "/portraits/generated-ai/npc-131.svg",
  "万三姑": "/portraits/generated-ai/npc-132.svg",
  "蛮胡子": "/portraits/generated-ai/npc-133.svg",
  "青易居士": "/portraits/generated-ai/npc-134.svg",
  "温天仁": "/portraits/generated-ai/npc-135.svg",
  "逆星盟主": "/portraits/generated-ai/npc-136.svg",
  "乌丑": "/portraits/generated-ai/npc-137.svg",
  "黑袍法士": "/portraits/generated-ai/npc-138.svg",
  "赤火老怪": "/portraits/generated-ai/npc-139.svg",
  "玄骨传人": "/portraits/generated-ai/npc-140.svg",
  "极阴祖师": "/portraits/generated-ai/npc-141.svg",
  "玄骨上人": "/portraits/generated-ai/npc-142.svg",
  "乌丑少主": "/portraits/generated-ai/npc-143.svg",
  "极阴门徒": "/portraits/generated-ai/npc-144.svg",
  "阴火道人": "/portraits/generated-ai/npc-145.svg",
  "骨焰真人": "/portraits/generated-ai/npc-146.svg",
  "白骨夫人": "/portraits/generated-ai/npc-147.svg",
  "噬魂子": "/portraits/generated-ai/npc-148.svg",
  "冥水散人": "/portraits/generated-ai/npc-149.svg",
  "寒魄童子": "/portraits/generated-ai/npc-150.svg",
  "青阳老魔": "/portraits/generated-ai/npc-151.svg",
  "青阳门主": "/portraits/generated-ai/npc-152.svg",
  "青阳使者": "/portraits/generated-ai/npc-153.svg",
  "火云道人": "/portraits/generated-ai/npc-154.svg",
  "赤阳子": "/portraits/generated-ai/npc-155.svg",
  "青火童子": "/portraits/generated-ai/npc-156.svg",
  "炎晶真人": "/portraits/generated-ai/npc-157.svg",
  "焚海客": "/portraits/generated-ai/npc-158.svg",
  "烈阳散人": "/portraits/generated-ai/npc-159.svg",
  "离火法士": "/portraits/generated-ai/npc-160.svg",
  "向之礼": "/portraits/generated-ai/npc-161.svg",
  "白老鬼": "/portraits/generated-ai/npc-162.svg",
  "太一门主": "/portraits/generated-ai/npc-163.svg",
  "玄一真人": "/portraits/generated-ai/npc-164.svg",
  "玉阳子": "/portraits/generated-ai/npc-165.svg",
  "太真道人": "/portraits/generated-ai/npc-166.svg",
  "清明居士": "/portraits/generated-ai/npc-167.svg",
  "太和散人": "/portraits/generated-ai/npc-168.svg",
  "云鹤真人": "/portraits/generated-ai/npc-169.svg",
  "太一执法": "/portraits/generated-ai/npc-170.svg",
  "乾老魔": "/portraits/generated-ai/npc-171.svg",
  "天魔宗主": "/portraits/generated-ai/npc-172.svg",
  "呼老魔": "/portraits/generated-ai/npc-173.svg",
  "魔焰门主": "/portraits/generated-ai/npc-174.svg",
  "阴芝马使": "/portraits/generated-ai/npc-175.svg",
  "黑风尊者": "/portraits/generated-ai/npc-176.svg",
  "血影魔君": "/portraits/generated-ai/npc-177.svg",
  "玄阴法王": "/portraits/generated-ai/npc-178.svg",
  "百损道人": "/portraits/generated-ai/npc-179.svg",
  "无相魔修": "/portraits/generated-ai/npc-180.svg",
  "车老妖": "/portraits/generated-ai/npc-181.svg",
  "万妖谷主": "/portraits/generated-ai/npc-182.svg",
  "银翅夜叉": "/portraits/generated-ai/npc-183.svg",
  "木魁": "/portraits/generated-ai/npc-184.svg",
  "圭灵": "/portraits/generated-ai/npc-185.svg",
  "啼魂兽": "/portraits/generated-ai/npc-186.svg",
  "毒圣门客": "/portraits/generated-ai/npc-187.svg",
  "青背妖修": "/portraits/generated-ai/npc-188.svg",
  "金蛟王": "/portraits/generated-ai/npc-189.svg",
  "白鹿妖君": "/portraits/generated-ai/npc-190.svg",
  "小极宫主": "/portraits/generated-ai/npc-191.svg",
  "白瑶怡": "/portraits/generated-ai/npc-192.svg",
  "寒骊上人": "/portraits/generated-ai/npc-193.svg",
  "冰凤": "/portraits/generated-ai/npc-194.svg",
  "小极长老": "/portraits/generated-ai/npc-195.svg",
  "玄冰仙子": "/portraits/generated-ai/npc-196.svg",
  "寒月道人": "/portraits/generated-ai/npc-197.svg",
  "雪魄真人": "/portraits/generated-ai/npc-198.svg",
  "冰魄童子": "/portraits/generated-ai/npc-199.svg",
  "北冥散人": "/portraits/generated-ai/npc-200.svg",
};

export function portraitFor(person) {
  if (!person?.name) return "";
  if (person.id === "player" || person.isPlayer) {
    return Number(person.portraitVariant || 0) === 1
      ? "/portraits/custom/lixinshu-web.webp"
      : "/portraits/generated/han-li-web.webp";
  }
  if (portraitMap[person.name]) return portraitMap[person.name];
  return dicebearPortraitFor(person);
}

const generatedPortraits = new Map();
const rootPalette = {
  earth: ["b7a17a", "d7c29a", "6b5a3e"],
  fire: ["db735c", "f2b36d", "6f2d24"],
  heaven: ["97a8d8", "d7c6ff", "38416f"],
  metal: ["d8c27a", "f4e3a1", "6b5b33"],
  water: ["6fb7d6", "b7e1ef", "214a82"],
  wood: ["74b989", "c6e4b8", "245c47"]
};

function dicebearPortraitFor(person) {
  const seed = [person.id, person.name, person.sect, person.primaryRootKey || person.root?.key].filter(Boolean).join("-");
  if (generatedPortraits.has(seed)) return generatedPortraits.get(seed);

  const rootKey = person.primaryRootKey || person.root?.key || "wood";
  const avatar = createAvatar(person.gender === "female" ? adventurerNeutral : adventurer, {
    seed,
    backgroundColor: rootPalette[rootKey] || rootPalette.wood,
    backgroundType: ["gradientLinear"],
    radius: 12,
    size: 128
  });
  const uri = avatar.toDataUri();
  generatedPortraits.set(seed, uri);
  return uri;
}
